branch-defaults:
  2-aws-deploy:
    environment: hotelBooking-dev
    group_suffix: null
global:
  application_name: hotelBooking
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
